// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUF4f3lYRUs8JMrT8SO39FRTpPyetalHI',
    appId: '1:747670137302:web:7fc906019ae8a3d6229c77',
    messagingSenderId: '747670137302',
    projectId: 'fir-authentication-eb762',
    authDomain: 'fir-authentication-eb762.firebaseapp.com',
    storageBucket: 'fir-authentication-eb762.firebasestorage.app',
    measurementId: 'G-BCNWZV7WLS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9E5mZEH74EFzpJh6_KRTIEnOpQlhfBRk',
    appId: '1:747670137302:android:e4ff6ec6752de5d9229c77',
    messagingSenderId: '747670137302',
    projectId: 'fir-authentication-eb762',
    storageBucket: 'fir-authentication-eb762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWPGD364-EBiK1da6ADDRmzbWY3yL4frs',
    appId: '1:747670137302:ios:f96f90ff590962f3229c77',
    messagingSenderId: '747670137302',
    projectId: 'fir-authentication-eb762',
    storageBucket: 'fir-authentication-eb762.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWPGD364-EBiK1da6ADDRmzbWY3yL4frs',
    appId: '1:747670137302:ios:f96f90ff590962f3229c77',
    messagingSenderId: '747670137302',
    projectId: 'fir-authentication-eb762',
    storageBucket: 'fir-authentication-eb762.firebasestorage.app',
    iosBundleId: 'com.example.week5Project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUF4f3lYRUs8JMrT8SO39FRTpPyetalHI',
    appId: '1:747670137302:web:f84c73450ef24f5a229c77',
    messagingSenderId: '747670137302',
    projectId: 'fir-authentication-eb762',
    authDomain: 'fir-authentication-eb762.firebaseapp.com',
    storageBucket: 'fir-authentication-eb762.firebasestorage.app',
    measurementId: 'G-VYPH0XTX90',
  );
}
